"""add scan scheduling fields to assets

Revision ID: c512b9a3c239
Revises: a72273fb6dbe
Create Date: 2026-09-14 15:09:35.969105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c512b9a3c239'
down_revision: Union[str, Sequence[str], None] = 'a72273fb6dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('scan_frequency', sa.String(length=20), nullable=True))
    op.add_column('assets', sa.Column('last_scanned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_scanned_at')
    op.drop_column('assets', 'scan_frequency')
    # ### end Alembic commands ###
